name: Институт за развитие на съзнанието
favicon: null
layout_spectrum: 0.50859
typography_spectrum: 0.4804
title: Институт за развитие на съзнанието
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151539'
    - '#3b74cb'
    - '#8c9dc8'
    - '#8bcffe'
    - '#eafefd'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
