name: Consciousness development institute
favicon: null
layout_spectrum: 0.59323
typography_spectrum: 0.82241
title: Consciousness development institute
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151539'
    - '#3b74cb'
    - '#8c9dc8'
    - '#8bcffe'
    - '#eafefd'
  brandStrength: 0.4375
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 1
purpose: []
